application: bibliodiaspora
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app
- url: /_ah/login_required
  script: do_openid_login.app

libraries:
- name: jinja2
  version: latest
